# -*- coding: utf-8 -*-
"""text_augmentation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZzU3MekMkHRgDOD4y63mp_D1IhdcGztG
"""

#Mount the google drive
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# direct to the folder where the data located, change the folder path here if needed
# %cd '/content/drive/MyDrive/CSCE 638 NLP Project/LOL_Data/' 
!ls

!pip install google_trans_new

import pandas as pd
import time

from google_trans_new import google_translator

translator = google_translator()  

def German_translation(x):
  #print(x)    
  german_translation = translator.translate(x, lang_src='en', lang_tgt='de')    
  return german_translation

def English_translation(x):
  #print(x)    
  english_translation = translator.translate(x, lang_src='de', lang_tgt='en')    
  return english_translation

df_train = pd.read_csv('train8000.csv')
print(df_train.describe())
df_train = df_train[df_train['is_humor']==1]
print(df_train.describe())


fout = open('aug.tsv','a')
#fout.write('id,text,is_humor,humor_rating,humor_controversy,offense_rating\n') 
#aug_text = []
for r in range(1978, df_train.shape[0]):
  print(r)
  #time.sleep(2)
  id = df_train.iloc[r,0]
  text = df_train.iloc[r,1]
  is_humor = df_train.iloc[r,2]
  humor_rating = df_train.iloc[r,3]
  humor_controversy = df_train.iloc[r,4]
  offense_rating = df_train.iloc[r,5]
  
  ger = German_translation(text)
  eng = English_translation(ger)
  
  fout.write(str(id) + '\t' + eng + '\t'+ str(is_humor) + '\t' + str(humor_rating) + '\t' + str(humor_controversy) + '\t' + str(offense_rating) + '\n')
  #aug_text.append(eng)
  
  #if r ==5:
  #  stop

fout.close()

print(df_train.shape[0])
print(df_train.iloc[4395,0])